<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5dx0Pa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5dx0Pa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5dx0Pa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5dx0Pa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5dx0Pa\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5dx0Pa',
    'container.build_id' => 'e44541aa',
    'container.build_time' => 1638436406,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5dx0Pa');
