<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEllnPUj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEllnPUj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEllnPUj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEllnPUj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEllnPUj\App_KernelDevDebugContainer([
    'container.build_hash' => 'EllnPUj',
    'container.build_id' => 'b2792ced',
    'container.build_time' => 1639041155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEllnPUj');
